In [2]:
#OVERLOADING AND OVERRIDDING
def sum_num(*args):
    result=0
    for num in args:
        result+=num
    print("RESULT =",result)
print("SIMILER TO METHOD OVERLOADING",)
print("SINGLE ARGUMENT ->",end=" ")
sum_num(10)
print("TWO ARGUMENT ->",end=" ")
sum_num(10,20)
print("MULTIPLE ARGUMENT ->",end=" ")
sum_num(10,20,30,40,50)

SIMILER TO METHOD OVERLOADING
SINGLE ARGUMENT -> RESULT = 10
TWO ARGUMENT -> RESULT = 30
MULTIPLE ARGUMENT -> RESULT = 150


In [4]:
def fun(a):
    print("HELLO")
def fun(a,b):
    print("HII HOW ARE YOU")
def fun(a,b,c):
    print("WELCOME")
fun(10,20,30)

WELCOME


In [7]:
class A:
    def first(self):
        print("FIRST FUNCTION")
    def second(self):
        print("SECOND FUNCTION")
class B(A):
    def first(self):
        print("REDIFINED FUNCTION OF CLASS A IN CLASS B")
    def display(self):
        print("DISPLAY FUNCTION OF CHILD CLASS")
        
a=A()
b=B()
a.first()
a.second()
b.first()
b.display()

FIRST FUNCTION
SECOND FUNCTION
REDIFINED FUNCTION OF CLASS A IN CLASS B
DISPLAY FUNCTION OF CHILD CLASS


In [8]:
#OPERATOR OVERLOADING
print(2+3)
print("Hii "+"Hello ")
print([1,2,3]+[4,5,6])

5
Hii Hello 
[1, 2, 3, 4, 5, 6]


In [8]:
class A:
    def __init__(self,a):
        self.a=a
    def __add__(self,other):
        return self.a+other.a
obj1=A(5)
obj2=A(3)
obj3=A("HELLO")
obj4=A("HII")
print(obj1+obj2)
print(obj3+obj4)
print(obj1.__add__(obj2))
print(A.__add__(obj1,obj2))

8
HELLOHII
8
8


In [10]:
class A:
    def __init__(self,a):
        self.a=a
    def __gt__(self,other):
        if self.a>other.a:
            return True
        else:
            return False
obj1=A(5)
obj2=A(7)
if obj1>obj2:
    print("OBJ1 IS GREATER")
else:
    print("OBJ2 IS GREATER")

OBJ2 IS GREATER


In [11]:
#MATHEMATICAL OPERATORS
class A:
    def __init__(self,a):
        self.a=a
    def __ge__(self,other):
        if self.a>=other.a:
            return True
        else:
            return False
    def __le__(self,other):
        if self.a<=other.a:
            return True
        else:
            return False
    def __truediv__(self,other):
        return self.a/other.a
    def __floordiv__(self,other):
        return self.a//other.a

obj1=A(5)
obj2=A(4)
obj3=A(10)
obj4=A(20)
obj5=A(30)
if obj1>=obj2:
    print("obj1 is equal or greater")
else:
    print("obj2 is equal or greater")
if obj1<=obj2:
    print("obj1 is equal or less then")
else:
    print("obj2 is equal or less then")
print(obj3/obj2)
print(obj3//obj2)
print(obj5/obj4)
print(obj5//obj4)

obj1 is equal or greater
obj2 is equal or less then
2.5
2
1.5
1


In [12]:
#Single inheritance(Simple inheritance)
class parent:
    def fun1(self):
        print("HELLO")
class child(parent):
    def fun2(self):
        print("hii")
obj=child()
obj.fun1()
obj.fun2()

HELLO
hii


In [17]:
class parent1:
    def fun1(self):
        print("HELLO")
class parent2:
    def fun2(self):
        print("HOW ARE YOU")
class parent3:
    def fun2(self):
        print("HOW ARE YOU 2")
class child(parent1,parent3,parent2):
    def fun3(self):
        print("hii")
obj=child()
obj.fun1()
obj.fun2()
obj.fun3()
print(child.__mro__)

HELLO
HOW ARE YOU 2
hii
(<class '__main__.child'>, <class '__main__.parent1'>, <class '__main__.parent3'>, <class '__main__.parent2'>, <class 'object'>)


In [18]:
#Multilevel inheritace
class grandparent:
    def fun1(self):
        print("Hello GrandParent")
class parent(grandparent):
    def fun2(self):
        print("Hello Parent")
class child(parent):
    def fun3(self):
        print("Hello Child")
        
obj=child()
obj.fun1()
obj.fun2()
obj.fun3()
    

Hello GrandParent
Hello Parent
Hello Child


In [20]:
class parent:
    def fun1(self):
        print("Hello Parent")
class child1(parent):
    def fun2(self):
        print("Hello Child1")
class child2(parent):
    def fun3(self):
        print("Hello Child2")
obj1=child1()
obj2=child2()
obj1.fun1()
obj1.fun2()
obj2.fun1()
obj2.fun3()

Hello Parent
Hello Child1
Hello Parent
Hello Child2


In [6]:
class parent1:
    def fun1(self):
        print("Hello Parent1")
class parent2:
    def fun2(self):
        print("Hello Parent2")
class child1(parent1):
    def fun3(self):
        print("Hello Child1")
class child2(child1,parent2):
    def fun4(self):
        print("Hello Child2")
obj1=child1()
obj2=child2()
obj1.fun1()
obj1.fun3()
obj2.fun1()
obj2.fun2()
obj2.fun3()
obj2.fun4()

Hello Parent1
Hello Child1
Hello Parent1
Hello Parent2
Hello Child1
Hello Child2


In [4]:
#special function in python inheritance
#1)super()
class parent:
    def __init__(self):
        self.attr1=50
        self.attr2=60
class child(parent):
    def __init__(self):
        super().__init__()
        self.attr3=45
obj=child()
print(obj.attr3)
print(obj.attr1)
print(obj.attr2)

45
50
60


In [7]:
class parent:
    def display(self):
        print("Hello parent")
class child(parent):
    def display(self):
        super().display()
        print("Hello child")

obj=child()
obj.display()

Hello parent
Hello child


In [8]:
#2)issubclass
class parent:
    def fun1(self):
        print("Hello Parent")
class child(parent):
    def fun2(self):
        print("Hello Child")
print(issubclass(child,parent))
print(issubclass(parent,child))

True
False


In [11]:
#3)isinstance()
A=child()
B=parent()
print(isinstance(A,child))
print(isinstance(A,parent))
print(isinstance(B,child))
print(isinstance(B,parent))

True
True
False
True


In [18]:
# METHOD RESOLUTION ORDER
class A:
    def rk(self):
        print("Class A")
class B(A):
    def rk(self):
        print("Class B")
class C(A):
    def rk(self):
        print("Class C")
class D(B,C):
    pass

r=D()
r.rk()
print(D.__mro__)
print(D.mro())

Class B
(<class '__main__.D'>, <class '__main__.B'>, <class '__main__.C'>, <class '__main__.A'>, <class 'object'>)
[<class '__main__.D'>, <class '__main__.B'>, <class '__main__.C'>, <class '__main__.A'>, <class 'object'>]


In [36]:
class p1:
    def foo(self):
        print("foo from p1")
class p2:
    def foo(self):
        print("foo from p2")
    def bar(self):
        print("bar from p2")
class c1(p1,p2):
    pass
class c2(p2):
    def bar(self):
        print("bar from c2")
class GC(c1,c2):
    pass

obj=GC()
obj.bar()
obj.foo()
print(GC.__mro__)

bar from c2
foo from p1
(<class '__main__.GC'>, <class '__main__.c1'>, <class '__main__.p1'>, <class '__main__.c2'>, <class '__main__.p2'>, <class 'object'>)


In [35]:
#Abstract class
from abc import ABC,abstractmethod
class shape(ABC):
    def __init__(self,shape_name):
        self.shape_name=shape_name
    @abstractmethod
    def draw(self):
        print("Drawing :".self.shape_name)

class circle(shape):
    def __init__(self):
        super().__init__("Circle")
    def draw_circle(self):
        print("Drawing :",self.shape_name)
    def draw(self):
        pass
        
obj=circle()
obj.draw_circle()

Drawing : Circle


In [54]:
#class book -:name,,no ot authors,list of authors,publisher,isbn,year
#class coursr_book(book) -: +course_name
#overrides display method
class Book:
    def __init__(self,name,noofaut,listofaut,pub,isbn,year):
        self.name=name
        self.noofaut=noofaut
        self.listofaut=listofaut
        self.pub=pub
        self.isbn=isbn
        self.year=year
    def display(self):
        print("BOOK NAME :",self.name)
        print("NO OF AUTHORS :",self.noofaut)
        print("LIST OF AUTHORS :",self.listofaut)
        print("PUBLISHER :",self.pub)
        print("ISBN :",self.isbn)
        print("YEAR :",self.year)
        
class course_book(Book):
    def __init__(self,course_name,name,noofaut,listofaut,pub,isbn,year):
        super().__init__(name,noofaut,listofaut,pub,isbn,year)
        self.course_name=course_name
    def display(self):
        super().display()
        print("COURSE NAME :",self.course_name)
        
l=["ABC","XYZ"]
c=course_book("CSE","PYTHON1",2,["XYZ","ABC"],"PQR",1234,1999)
c.display()

BOOK NAME : PYTHON1
NO OF AUTHORS : 2
LIST OF AUTHORS : ['XYZ', 'ABC']
PUBLISHER : PQR
ISBN : 1234
YEAR : 1999
COURSE NAME : CSE


In [56]:
class student:
    def __init__(self,rollno,name,age,total_marks):
        self.rollno=rollno
        self.name=name
        self.age=age
        self.total_marks=total_marks
    def display(self):
        print("ROLL NO:",self.rollno)
        print("NAME :",self.name)
        print("AGE :",self.age)
        print("TOTAL MARKS :",self.total_marks)
    def __eq__(self,other):
        if self.total_marks==other.total_marks:
            return True
        else:
            return False
    
s1=student(1,"JAIV",20,98)
s2=student(2,"HARSHIT",21,98)
if s1==s2:
    print("EQUAL")
else:
    print("NOT EQUAL")

EQUAL


In [24]:
class Bill:
        total=0
        HDD=5000
        RAM=2000
        PRINTER=6000
        PENDRIVE=800
        print("HDD 5000")
        in1=input("WANT THIS ITEM ?(Y/N)")
        if in1.upper()=="Y":
            qnt1=int(input("ENTER NO OF HDD'S :"))
            total+=(HDD*qnt1)
        print("RAM 2000")
        in1=input("WANT THIS ITEM ?(Y/N)")
        if in1.upper()=="Y":
            qnt2=int(input("ENTER NO OF RAM'S :"))
            total+=(RAM*qnt2)
        print("PRINTER 6000")
        in1=input("WANT THIS ITEM ?(Y/N)")
        if in1.upper()=="Y":
            qnt3=int(input("ENTER NO OF PRINTER'S :"))
            total+=(PRINTER*qnt3)
        print("PENDRIVE 800")
        in1=input("WANT THIS ITEM ?(Y/N)")
        if in1.upper()=="Y":
            qnt4=int(input("ENTER NO OF PENDRIVE'S :"))
            total+=(PENDRIVE*qnt4)
        def __init__(self):
            print("PAYMENT METHOD :")
            print("1 CASH PAYMENT")
            print("2 CHEQUE PAYMENT")
            m=int(input("ENTER PAYMENT METHOD NO :"))
            if m==1:
                cashpayment()
            elif m==2:
                chequepayment()
            else:
                print("ENTER VALID CHOICE")
            
class cashpayment(Bill):
    def __init__(self):
        print("TOTAL AMOUNT TO PAY =",super().total)
        self.n2000=super().total//2000
        self.n500=(super().total%2000)//500
        self.n200=((super().total%2000)%500)//200
        self.n100=(((super().total%2000)%500)%200)//100
        if self.n2000>=1:
            print("2000 RS NOTES :: ",self.n2000)
        if self.n500>=1:
            print("500 RS NOTES :: ",self.n500)
        if self.n200>=1:
            print("200 RS NOTES :: ",self.n200)
        if self.n100>=1:
            print("100 RS NOTES :: ",self.n100)
            
class chequepayment(Bill):
    def __init__(self):
        print("TOTAL AMOUNT TO PAY =",super().total)
        self.chno=input("ENTER CHEQUE NO :")
        self.bank=input("ENTER BANK NAME")
        print("CHEQUE PAYMENT :")
        print("CHEQUE NO :",self.chno)
        print("BANK NAME :",self.bank)
        
a=Bill()

HDD 5000
WANT THIS ITEM ?(Y/N)y
ENTER NO OF HDD'S :1
RAM 2000
WANT THIS ITEM ?(Y/N)y
ENTER NO OF RAM'S :1
PRINTER 6000
WANT THIS ITEM ?(Y/N)y
ENTER NO OF PRINTER'S :1
PENDRIVE 800
WANT THIS ITEM ?(Y/N)y
ENTER NO OF PENDRIVE'S :1
PAYMENT METHOD :
1 CASH PAYMENT
2 CHEQUE PAYMENT
ENTER PAYMENT METHOD NO :2
TOTAL AMOUNT TO PAY = 13800
ENTER CHEQUE NO :12345
ENTER BANK NAMESBI
CHEQUE PAYMENT :
CHEQUE NO : 12345
BANK NAME : SBI


In [26]:
# NUMPY
import numpy as np
import sys
s=range(1000)
print("SIZE OF EACH ELEMENT IF LIST IN BYTES ",sys.getsizeof(s))
print("SIZE OF WHOLE LIST IN BYTES :",sys.getsizeof(s)*len(s))

SIZE OF EACH ELEMENT IF LIST IN BYTES  48
SIZE OF WHOLE LIST IN BYTES : 48000


In [28]:
d=np.arange(1000)
print("SIZE OF EACH ELEMENT OF NUMPY ARRAY IN BYTES :",d.itemsize)
print("SIZE OF WHOLE NUMPY ARRAY IN BYTES :",d.itemsize*d.size)

SIZE OF EACH ELEMENT OF NUMPY ARRAY IN BYTES : 4
SIZE OF WHOLE NUMPY ARRAY IN BYTES : 4000


In [31]:
import numpy as np
arr=np.array(42)
print(type(arr))
print(arr.ndim)

<class 'numpy.ndarray'>
0


In [44]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr[0:2,0:2,0:2])
print(arr.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]
(2, 2, 3)


In [45]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,:3])
print(arr[:1,:3])
print(arr[1:])
print(arr.shape)

[6 7 8]
[[1 2 3]]
[[ 6  7  8  9 10]]
(2, 5)


In [49]:
import numpy as np
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)


In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.shape)


[1 2 3 4 5]
(5,)


In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=arr.reshape(2,3,1).base
print(newarr)

[1 2 3 4 5 6]


In [3]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=arr.reshape(2,-1)
print(newarr)

[[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=arr.reshape(-1,3)
print(newarr)

[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
for x in arr:
    print(x)

1
2
3
4
5
6


In [7]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for c in arr:
    for j in c:
        print(j)


1
2
3
4
5
6


In [11]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for c in arr:
    for j in c:
        for y in j:
            print(y)
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12


In [10]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for c in np.nditer(arr):
    print(c)

1
2
3
4
5
6
7
8
9
10
11
12


In [12]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[0:1,::2]):
    print(x)

1
3


In [13]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:,::2]):
    print(x)

1
3
5
7


In [14]:
#Built in function
#1)concatenate()
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
arr=np.concatenate((arr1,arr2,arr3))
print(arr)

[1 2 3 4 5 6 7 8 9]


In [18]:
arr1=np.array([[1,2],[5,6]])
arr2=np.array([[3,4],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [19]:
#2)split()
arr1=np.array([1,2,3,4])
arr=np.array_split(arr1,4)
print(arr)

[array([1]), array([2]), array([3]), array([4])]


In [20]:
arr1=np.array([1,2,3,4])
arr=np.array_split(arr1,3)
print(arr)

[array([1, 2]), array([3]), array([4])]


In [21]:
arr1=np.array([1,2,3,4])
arr=np.array_split(arr1,5)
print(arr)

[array([1]), array([2]), array([3]), array([4]), array([], dtype=int32)]


In [22]:
arr1=np.array([[1,2],[3,4],[5,6],[7,8]])
newarr=np.array_split(arr1,4,axis=1)
print(newarr)

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int32), array([], shape=(4, 0), dtype=int32)]


In [25]:
#3)where
arr1=np.array([1,2,3,4,5,6,4,2,3])
x=np.where(arr1==4)
print(x)

y=np.where(arr1%2==0)
print(y)

(array([3, 6], dtype=int64),)
(array([1, 3, 5, 6, 7], dtype=int64),)


In [26]:
arr1=np.array([[1,2],[3,4],[5,6],[4,8]])
x=np.where(arr1==4)
print(x)

(array([1, 3], dtype=int64), array([1, 0], dtype=int64))


In [29]:
arr=np.array([[[1,2,3,4],[4,5,7,6]],[[7,8,9,4],[9,10,11,12]]])
x=np.where(arr==4)
print(x)

(array([0, 0, 1], dtype=int64), array([0, 1, 0], dtype=int64), array([3, 0, 3], dtype=int64))


In [34]:
#4)sort()
arr1=np.array([1,2,3,4,5,6,4,2,3])
x=np.sort(arr1)
print(x)

arr2=np.array(['apple','cherry','banana'])
y=np.sort(arr2)
print(y)
ar3=np.array([True,False,True])
z=np.sort(ar3)
print(z)

[1 2 2 3 3 4 4 5 6]
['apple' 'banana' 'cherry']
[False  True  True]


In [42]:
arr1=np.array([[3,4,2],[1,7,3],[4,2,5]])
print(np.sort(arr1,axis=1))

[[2 3 4]
 [1 3 7]
 [2 4 5]]


In [48]:
arr1=np.array([[[3,2,8],[7,9,3]],[[6,7,2],[9,6,4]]])
print(np.sort(arr1))
print("-------------")
print(np.sort(arr1,axis=0))
print("-------------")
print(np.sort(arr1,axis=1))

[[[2 3 8]
  [3 7 9]]

 [[2 6 7]
  [4 6 9]]]
-------------
[[[3 2 2]
  [7 6 3]]

 [[6 7 8]
  [9 9 4]]]
-------------
[[[3 2 3]
  [7 9 8]]

 [[6 6 2]
  [9 7 4]]]


In [67]:
from numpy import random
x=random.randint(90,100)
print(x)

93


In [70]:
y=random.randint(10,100,size=(5))
print(y)
z=random.randint(10,100,size=(3,5))
print(z)

[67 14 62 38 42]
[[46 90 88 20 62]
 [44 47 64 28 55]
 [19 80 56 20 27]]


In [73]:
#2)rand
x=random.rand()
print(x)

x=random.rand(5)
print(x)

x=random.rand(3,5)
print(x)

0.6370564077598626
[0.73708189 0.02365469 0.86964194 0.44660498 0.15334716]
[[0.50104773 0.86739896 0.89042577 0.65707211 0.87667582]
 [0.20481715 0.3134774  0.16658635 0.95973277 0.83154924]
 [0.34822344 0.12552317 0.34902963 0.40948788 0.97361539]]


In [78]:
#3)choice
x=random.choice([1,3,5,7,9])
print(x)

x=random.choice([1,3,5,7,9],size=(5))
print(x)

3
[9 5 9 1 9]


In [8]:
from numpy import random
i=0
r=random.randint(100)
while i<7:
    i+=1
    g=int(input("GUESS A NUMBER BETWEEN 1-99 :"))
    if g==r:
        print("YOU WIN")
        print("NUMBER IS",r)
        break
    else:
        if(g>r):
            print("NUMBER IS LESS THEN YOU GUESS")
        elif(g<r):
            print("NUMBER IS MORE THEN YOU GUESS")
        print(7-i,"ATTEMPS LEFT")
        if(7-i==0):
            print("SORRY NUMBER=",r)
        
    

GUESS A NUMBER BETWEEN 1-99 :60
NUMBER IS LESS THEN YOU GUESS
6 ATTEMPS LEFT
GUESS A NUMBER BETWEEN 1-99 :50
NUMBER IS LESS THEN YOU GUESS
5 ATTEMPS LEFT
GUESS A NUMBER BETWEEN 1-99 :4
NUMBER IS MORE THEN YOU GUESS
4 ATTEMPS LEFT
GUESS A NUMBER BETWEEN 1-99 :40
NUMBER IS LESS THEN YOU GUESS
3 ATTEMPS LEFT
GUESS A NUMBER BETWEEN 1-99 :30
NUMBER IS MORE THEN YOU GUESS
2 ATTEMPS LEFT
GUESS A NUMBER BETWEEN 1-99 :35
NUMBER IS LESS THEN YOU GUESS
1 ATTEMPS LEFT
GUESS A NUMBER BETWEEN 1-99 :34
YOU WIN
NUMBRT IS 34
